# Generated by Django 6.0.6 on 2026-07-21 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scraperrun',
            name='source',
            field=models.CharField(choices=[('aqarmap', 'Aqarmap'), ('bayut', 'Bayut'), ('nawy', 'Nawy'), ('manual', 'User Posted')], max_length=20),
        ),
    ]
