# Generated by Django 6.0.6 on 2026-07-22 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_passwordresetcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='whatsapp',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
