# Generated by Django 6.0.6 on 2026-06-23 20:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='listing_type',
            field=models.CharField(blank=True, choices=[('for_sale', 'For Sale'), ('for_rent', 'For Rent')], max_length=10),
        ),
        migrations.AlterField(
            model_name='listing',
            name='source',
            field=models.CharField(choices=[('manual', 'User Posted'), ('bayut', 'Bayut'), ('aqarmap', 'Aqarmap'), ('facebook', 'Facebook Marketplace')], default='manual', max_length=20),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['listing_type'], name='listings_li_listing_f8edcf_idx'),
        ),
    ]
