# Generated by Django 6.0.6 on 2026-06-23 13:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_listing_city'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='address',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='listing',
            name='city',
            field=models.CharField(blank=True, choices=[('cairo', 'Cairo'), ('alexandria', 'Alexandria'), ('giza', 'Giza'), ('new_capital', 'New Capital'), ('6th_of_october', '6th of October'), ('sharm_el_sheikh', 'Sharm El Sheikh'), ('hurghada', 'Hurghada'), ('mansoura', 'Mansoura'), ('tanta', 'Tanta'), ('luxor', 'Luxor'), ('aswan', 'Aswan'), ('suez', 'Suez'), ('ismailia', 'Ismailia'), ('port_said', 'Port Said'), ('zagazig', 'Zagazig')], max_length=50),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['city'], name='listings_li_city_e45c53_idx'),
        ),
    ]
