# Generated by Django 6.0.6 on 2026-06-24 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_listing_listing_type_alter_listing_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='source',
            field=models.CharField(choices=[('manual', 'User Posted'), ('bayut', 'Bayut'), ('aqarmap', 'Aqarmap'), ('nawy', 'Nawy')], default='manual', max_length=20),
        ),
    ]
