# Generated by Django 6.0.6 on 2026-07-21 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_listing_latitude_listing_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='property_type',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
